FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

ARG MOBISCROLL_TOKEN
ARG NEXT_PUBLIC_AUTH_SERVICE_URL
ARG NEXT_PUBLIC_LISTING_SERVICE_URL
ARG NEXT_PUBLIC_BOOKING_SERVICE_URL
ARG NEXT_PUBLIC_PAYMENT_SERVICE_URL
ARG NEXT_PUBLIC_COMMUNICATION_SERVICE_URL
ARG NEXT_PUBLIC_REVIEW_SERVICE_URL
ARG NEXT_PUBLIC_PRICING_SERVICE_URL

# Export vars so Next.js can read them during build
ENV NEXT_PUBLIC_AUTH_SERVICE_URL=$NEXT_PUBLIC_AUTH_SERVICE_URL
ENV NEXT_PUBLIC_LISTING_SERVICE_URL=$NEXT_PUBLIC_LISTING_SERVICE_URL
ENV NEXT_PUBLIC_BOOKING_SERVICE_URL=$NEXT_PUBLIC_BOOKING_SERVICE_URL
ENV NEXT_PUBLIC_PAYMENT_SERVICE_URL=$NEXT_PUBLIC_PAYMENT_SERVICE_URL
ENV NEXT_PUBLIC_COMMUNICATION_SERVICE_URL=$NEXT_PUBLIC_COMMUNICATION_SERVICE_URL
ENV NEXT_PUBLIC_REVIEW_SERVICE_URL=$NEXT_PUBLIC_REVIEW_SERVICE_URL
ENV NEXT_PUBLIC_PRICING_SERVICE_URL=$NEXT_PUBLIC_PRICING_SERVICE_URL

RUN echo "@mobiscroll:registry=https://npm.mobiscroll.com" >> ~/.npmrc \
    && echo "//npm.mobiscroll.com/:_authToken=${MOBISCROLL_TOKEN}" >> ~/.npmrc \
    && echo "legacy-peer-deps=true" >> ~/.npmrc

# Fix Mobiscroll checksum issues (npm 10+ compatible)
RUN rm -f package-lock.json \
    && npm config set strict-ssl false

# Install dependencies
RUN npm install --legacy-peer-deps --force

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
